<a href="https://colab.research.google.com/github/NouranOuf/Email-Spam-Detection/blob/main/data_analytics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import nltk

In [ ]:
#upload the data to colab
from google.colab import files
upload = files.upload()

In [ ]:
#load the data
data= pd.read_csv('data_spam.csv' , encoding='latin-1')
data

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN
...,...,...,...,...,...
5567,spam,This is the 2nd time we have tried 2 contact u...,NaN,NaN,NaN
5568,ham,Will Ì_ b going to esplanade fr home?,NaN,NaN,NaN
5569,ham,"Pity, * was in mood for that. So...any other s...",NaN,NaN,NaN
5570,ham,The guy did some bitching but I acted like i'd...,NaN,NaN,NaN
5571,ham,Rofl. Its true to its name,NaN,NaN,NaN

In [ ]:
data.columns

Index(['v1', 'v2', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'], dtype='object')

In [ ]:
# drop the anonymous cols
data.drop(['Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'] , axis =  1 , inplace = True)
data

        v1                                                 v2
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will Ì_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [ ]:
#basic preprocessing drop the duplicate rows
data.drop_duplicates(inplace=True)
data.shape

(5169, 2)

In [ ]:
#check for missing values in cols
data.isnull().sum()
#no missing data

v1    0
v2    0
dtype: int64

In [ ]:
#change cols name v1 to type and v2 to email
data = data.rename(columns={'v1': 'Type', 'v2': 'Email'})
data

      Type                                              Email
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will Ì_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [ ]:
# convert the class to binary classification as sklearn deals with numerical data only
data.classify[data.classify == 'spam'] = 1
data.classify[data.classify == 'ham'] = 0
data

     classify                                               mail
0           0  Go until jurong point, crazy.. Available only ...
1           0                      Ok lar... Joking wif u oni...
2           1  Free entry in 2 a wkly comp to win FA Cup fina...
3           0  U dun say so early hor... U c already then say...
4           0  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567        1  This is the 2nd time we have tried 2 contact u...
5568        0              Will Ì_ b going to esplanade fr home?
5569        0  Pity, * was in mood for that. So...any other s...
5570        0  The guy did some bitching but I acted like i'd...
5571        0                         Rofl. Its true to its name

[5169 rows x 2 columns]

In [ ]:
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')
from nltk.corpus import stopwords

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...

In [ ]:
from nltk.stem import WordNetLemmatizer
import string

def process_mail (mail):
  #remove stopwords
  #remove punc
  # change to lower case
  # perform lemmatization
  stops = set(stopwords.words("english"))
  nonpunc = [char for char in mail if char not in string.punctuation]
  nonpunc = ''.join(nonpunc)
  nonpunc = nonpunc.lower()
  words = [word for word in nonpunc.split() if word not in  stops]
  lemmatizer=WordNetLemmatizer()
  clean_words = [lemmatizer.lemmatize(w) for w in words]
  return clean_words

In [ ]:
data['Email'].head().apply(process_mail)

0    [go, jurong, point, crazy, available, bugis, n...
1                       [ok, lar, joking, wif, u, oni]
2    [free, entry, 2, wkly, comp, win, fa, cup, fin...
3        [u, dun, say, early, hor, u, c, already, say]
4    [nah, dont, think, go, usf, life, around, though]
Name: Email, dtype: object

In [ ]:
#filter tokens by Pos tags
nltk.download('averaged_perceptron_tagger')
data['splitted'] = data['Email'].str.split(" ")
data['splitted']

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!

0       [Go, until, jurong, point,, crazy.., Available...
1                    [Ok, lar..., Joking, wif, u, oni...]
2       [Free, entry, in, 2, a, wkly, comp, to, win, F...
3       [U, dun, say, so, early, hor..., U, c, already...
4       [Nah, I, don't, think, he, goes, to, usf,, he,...
                              ...
5567    [This, is, the, 2nd, time, we, have, tried, 2,...
5568       [Will, Ì_, b, going, to, esplanade, fr, home?]
5569    [Pity,, *, was, in, mood, for, that., So...any...
5570    [The, guy, did, some, bitching, but, I, acted,...
5571                    [Rofl., Its, true, to, its, name]
Name: splitted, Length: 5572, dtype: object

In [ ]:
data['tagged'] = data['splitted'].apply(nltk.pos_tag)
data['tagged']

0       [(Go, NNP), (until, IN), (jurong, JJ), (point,...
1       [(Ok, NNP), (lar..., VBZ), (Joking, NNP), (wif...
2       [(Free, JJ), (entry, NN), (in, IN), (2, CD), (...
3       [(U, JJ), (dun, NNS), (say, VBP), (so, RB), (e...
4       [(Nah, NNP), (I, PRP), (don't, VBP), (think, V...
                              ...
5567    [(This, DT), (is, VBZ), (the, DT), (2nd, JJ), ...
5568    [(Will, MD), (Ì_, VB), (b, NN), (going, VBG), ...
5569    [(Pity,, NNP), (*, NNP), (was, VBD), (in, IN),...
5570    [(The, DT), (guy, NN), (did, VBD), (some, DT),...
5571    [(Rofl., NNP), (Its, PRP$), (true, JJ), (to, T...
Name: tagged, Length: 5572, dtype: object

In [ ]:
data.drop(['splitted'] , axis =  1 , inplace = True)
data

,classify,mail,tagged
0,0,"Go until jurong point, crazy.. Available only ...","[(Go, NNP), (until, IN), (jurong, JJ), (point,..."
1,0,Ok lar... Joking wif u oni...,"[(Ok, NNP), (lar..., VBZ), (Joking, NNP), (wif..."
2,1,Free entry in 2 a wkly comp to win FA Cup fina...,"[(Free, JJ), (entry, NN), (in, IN), (2, CD), (..."
3,0,U dun say so early hor... U c already then say...,"[(U, JJ), (dun, NNS), (say, VBP), (so, RB), (e..."
4,0,"Nah I don't think he goes to usf, he lives aro...","[(Nah, NNP), (I, PRP), (don't, VBP), (think, V..."
...,...,...,...
5567,1,This is the 2nd time we have tried 2 contact u...,"[(This, DT), (is, VBZ), (the, DT), (2nd, JJ), ..."
5568,0,Will Ì_ b going to esplanade fr home?,"[(Will, MD), (Ì_, VB), (b, NN), (going, VBG), ..."
5569,0,"Pity, * was in mood for that. So...any other s...","[(Pity,, NNP), (*, NNP), (was, VBD), (in, IN),..."
5570,0,The guy did some bitching but I acted like i'd...,"[(The, DT), (guy, NN), (did, VBD), (some, DT),..."
5571,0,Rofl. Its true to its name,"[(Rofl., NNP), (Its, PRP$), (true, JJ), (to, T..."

In [ ]:
#feature generation
# bag of words is one word embedding techinques
#we can determine which to use based on the accuracy
from sklearn.feature_extraction.text import CountVectorizer
mail = CountVectorizer(analyzer=process_mail).fit_transform(data['Email'])
print(mail)

  (0, 3573)	1
  (0, 4426)	1
  (0, 6036)	1
  (0, 2369)	1
  (0, 1351)	1
  (0, 1789)	1
  (0, 5324)	1
  (0, 3664)	1
  (0, 8583)	1
  (0, 4577)	1
  (0, 2861)	1
  (0, 1787)	1
  (0, 2104)	1
  (0, 3626)	1
  (0, 1127)	1
  (0, 8363)	1
  (1, 5631)	1
  (1, 4613)	1
  (1, 4396)	1
  (1, 8488)	1
  (1, 8039)	1
  (1, 5662)	1
  (2, 3378)	1
  (2, 2989)	2
  (2, 412)	1
  :	:
  (5568, 3589)	1
  (5568, 8897)	1
  (5568, 3365)	1
  (5568, 3016)	1
  (5569, 5226)	1
  (5569, 7466)	1
  (5569, 5965)	1
  (5569, 7123)	1
  (5570, 8039)	1
  (5570, 3378)	1
  (5570, 8407)	1
  (5570, 4089)	1
  (5570, 4712)	1
  (5570, 5420)	1
  (5570, 7147)	1
  (5570, 2935)	1
  (5570, 3490)	1
  (5570, 1821)	1
  (5570, 3721)	1
  (5570, 4220)	1
  (5570, 955)	1
  (5570, 1586)	1
  (5571, 5337)	1
  (5571, 7976)	1
  (5571, 6614)	1

In [ ]:
from sklearn.model_selection import train_test_split

#split the data into 80:20
x_train, x_test, y_train, y_test = train_test_split(mail, data['Email'], test_size = 0.2, random_state = 0)
print(x_train)

  (0, 3947)	2
  (0, 4446)	1
  (0, 7922)	1
  (0, 5516)	1
  (0, 3685)	1
  (0, 2851)	1
  (1, 3589)	1
  (1, 3011)	1
  (1, 5142)	1
  (1, 8364)	1
  (1, 7720)	1
  (1, 4463)	1
  (2, 6582)	2
  (2, 5206)	1
  (2, 4665)	1
  (2, 4859)	1
  (2, 5834)	1
  (2, 975)	1
  (2, 8328)	1
  (2, 3895)	1
  (2, 7298)	1
  (2, 8513)	1
  (2, 8234)	1
  (3, 8188)	1
  (3, 2135)	1
  :	:
  (4454, 6736)	1
  (4454, 4623)	1
  (4454, 1819)	1
  (4454, 4431)	1
  (4454, 8900)	1
  (4454, 7898)	1
  (4454, 2488)	1
  (4454, 5724)	1
  (4454, 5713)	1
  (4454, 2672)	1
  (4454, 8330)	1
  (4455, 4712)	1
  (4455, 4782)	1
  (4455, 8733)	1
  (4455, 2647)	1
  (4455, 6616)	1
  (4455, 4866)	1
  (4455, 7311)	1
  (4456, 7585)	1
  (4456, 8562)	2
  (4456, 7647)	1
  (4456, 1184)	1
  (4456, 3820)	1
  (4456, 7427)	1
  (4456, 2477)	1

In [ ]:
# NAIVE BAYES CLASSIFIER
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score
from sklearn.tree import DecisionTreeClassifier

# train
classifier = MultinomialNB().fit(x_train, y_train)

# evaluate the model
prediction = classifier.predict(x_test)

accuracy = accuracy_score(y_test, prediction)
recall = recall_score(y_test, prediction)
precision = precision_score(y_test, prediction)
f1_score1 = f1_score(y_test, prediction)

# printing
print('Accuracy: ',accuracy)
print('Recall: ',recall)
print('Precision: ',precision)
print('F1-score: ',f1_score1)

Accuracy:  0.9574468085106383
Recall:  0.9194630872483222
Precision:  0.8106508875739645
F1-score:  0.8616352201257862

In [ ]:
# SVM
from sklearn import svm

#train

# when using kernel, accuracy = 0.97 otherwise when not using, accuracy = 0.95
model = svm.SVC(kernel = 'linear')
model.fit(x_train, y_train)

#evaluate
prediction_svm= model.predict(x_test)

accuracy_svm = accuracy_score(y_test,prediction_svm)
recall_svm = recall_score(y_test, prediction_svm)
precision_svm = precision_score(y_test, prediction_svm)
f1_score1_svm = f1_score(y_test, prediction_svm)

#printing
print('SVM Accuracy:',accuracy_svm)
print('recall: ',recall_svm)
print('Precision: ',precision_svm)
print('F1-score: ',f1_score1_svm)

SVM Accuracy: 0.9787234042553191
recall:  0.8523489932885906
Precision:  1.0
F1-score:  0.9202898550724637

In [ ]:
#Creating & Training Data With Decision Tree
Entropy = DecisionTreeClassifier(criterion = "gini" , random_state = 0 ,max_depth = 10 , min_samples_leaf=6)
Entropy.fit(x_train,y_train)

#Evaluting the data
pred = Entropy.predict(x_test)

# printing
print('Accuracy : ', accuracy_score(y_test,pred))
print('Precision : ', precision_score(y_test, pred))
print('Recall : ', recall_score(y_test, pred))
print('f1_score : ', f1_score(y_test,pred))

Accuracy :  0.9410058027079303
Precision :  0.9489795918367347
Recall :  0.6241610738255033
f1_score :  0.7530364372469635